name: Build and Deploy Code
# what triggers our code to run

on: [push, pull_request]
jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - name: pulling get repo
              uses: actions/checkout@2
            - name: sayhi to togay
              run: echo "hello Togay"


